//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixmensCMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPARACIONESVIEW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPARACIONESVIEW()
        {
            this.SMS = new HashSet<SMS>();
        }
    
        public long CODIGO { get; set; }
        public string EQUIPO { get; set; }
        public string NOMBRES { get; set; }
        public string FALLA { get; set; }
        public string INFORMETALLER { get; set; }
        public string DETALLE { get; set; }
        public string PRESPUPUESTO { get; set; }
        public string TECNICO { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO { get; set; }
        public Nullable<System.DateTime> PROMETIDO { get; set; }
        public Nullable<System.DateTime> FECHATERMINADO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHAUPDATE { get; set; }
        public string CELULAR { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ENTREGADO { get; set; }
        public string NS { get; set; }
        public Nullable<System.DateTime> FECHAENTREGADO { get; set; }
        public Nullable<bool> AVISADO { get; set; }
        public string COLOR { get; set; }
        public string ESTADOEQUIPO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMS> SMS { get; set; }
    }
}
